### ISSUE TITLE
Background traffic in the TAS simulator

### ISSUE THREAD

**Issue by RyderCRD** [ChuanyuXue/tsnkit#21]
We're implementing a new algorithm named [E-TSN](https://ieeexplore.ieee.org/abstract/document/9912262/) based on tsnkit. Different from the current 17 time-triggered algorithms, E-TSN can support event-triggered traffic with arbitrary arrival times.

However, it seems the current TAS simulator only verifies the GCL under critical traffic, without considering the influence of the background/best-effort traffic. So we can verify GCL effectiveness, but can't compare the performance of the streams being protected and unprotected. Are there any recent plans to include the background streams in the simulator? so that we don't need to turn to INET/OMNeT++ and write C++... 

tsnkit is nice and clear :) it will be a very promising platform for TSN simulation if it can also include background traffic consideration.

**Comment by ChuanyuXue** [comment]
The current simulator is designed solely to verify the correctness of the algorithm. We have no immediate plans to integrate background traffic.

It can be done by adding some additional TT traffic entries in task.csv to act as dummy BE traffic. Then, adjust all TT traffic entries so that queue_index += 1, and set the queue index for BE traffic to 0.

But for your purposes I recommend using a professional C++ based TSN simulator. Because the current Python simulator tends to slow down significantly with larger network topologies or stream sets, due to Python’s inherent performance limitations
