### ISSUE TITLE
The inconsistency in delay handling when frames are sent from the source side in both the scheduling method and the simulation.

### ISSUE THREAD

**Issue by lxacc** [ChuanyuXue/tsnkit#6]
In the scheduling method within the code, for example, in smt_nw, I noticed that only the transmission delay is considered when frames are sent from the **source side**, without accounting for the processing delay. 
While this is typically reasonable, I found in **simulation.tas.p**y ,Even frames sent from the source side are subjected to processing delays. Is there any inconsistency or issue with this?

**Comment by ChuanyuXue** [comment]
Thank you for bringing this to our attention. The issue is confirmed.

To clarify, the processing delay on the source side should **NOT** be assumed. In other words, the end-to-end delay calculation should starts from when the frame arrived at the egress queue of first switch.

I will later review and align all scheduling methods and the simulator to ensure consistency. This is also supposed to be mentioned in the document. Thanks.

**Comment by ChuanyuXue** [comment]
Issues fixed and explanations added in the document. Thanks for the good catch!
