### ISSUE TITLE
 The list of potential errors is always empty

### ISSUE THREAD

**Issue by HalongL** [ChuanyuXue/tsnkit#7]
I've been trying various scheduling algorithms and I've noticed that no matter how I adjust the parameters. The list of potential errors is always empty?How do you get the scheduling success rate in the article?Thanks！

![sche](https://github.com/ChuanyuXue/tsnkit/assets/107486076/d299ef5a-6c37-4f01-aeb1-495452f5f582)

**Comment by ChuanyuXue** [comment]
Potential errors from simulation are used for validation purposes rather than determining schedulability. It means that simulated delay might be out of bound, which implies the scheduling method gives a `succ` result but failed to pass simulation validation (in this case you might double check if your algorithm implementation is correct). 

When you run the algorithm and get the output like following, where the `flag` field shows where the method is schedulable on a stream set + network topology:

```
| time          | name   | flag   | solve_time | total_time | total_mem
| 19~14:48:54   | -      | succ   | 0.001      | 1.758      | 77072.0 
```

The `flag` field in the output indicates whether the scheduling method is successful (succ) for a given stream set and network topology. The schedulable ratio is basically calculated as the percentage of succ results out of the total number of datasets you have run.
